### ISSUE TITLE
Klassenbezeichnung MU23 WU23

### ISSUE THREAD

**Issue by thilopohl** [Deutscher-Leichtathletikverband/Interfaces#1]
Hallo zusammen,

im Rahmen der der DM U23 in Koblenz wurde die Diskussion geführt, wie die offizielle Langtext-Klassenbezeichnung der Klassen MU23 und WU23 lautet:

Variante 1 : Männer U23 / Frauen U23
Variante 2 : männliche U23 / weibliche U23
Variante 3 : Junioren U23 / Juniorinnen U23

Die DLV-Online-Bestenliste nutzt die Variante **1**
Seltec taf3 verwendet im Standard die Variante **1** 
Aus der DLO folgt eigentlich die Variante **2** 
In der neuen JSON Schnittstellen Altersklassen ist die Variante **3** vorgegeben
Die offizielle PDF-DLV Bestenliste wählt die Variante **3**
LADV nutzt Variante **3**

Es wäre gut, wenn hier eine abschließende Festlegung und Klärung erfolgen kann.

VG
Thilo

**Comment by UdoLaubDLV** [comment]
Wir haben inzwischen offizielle Disziplin - und Altersklassencodes mit Bezeichnungen, welche jeder Dienstleister nutzen sollte.
