### ISSUE TITLE
Unterschiedliche Ausgabe von "aufgegeben" in Mehrkämpfen in PDF<->Ergebnisdaten XML von Seltec (DED)

### ISSUE THREAD

**Issue by mschunk** [Deutscher-Leichtathletikverband/Interfaces#2]
Beobachtung: Bei Mehrkämpfen gibt es Unterschiede zwischen PDF Ergebnisliste und Ergebnisdaten XML die von Seltec (DED) erstellt wird. Insbesondere wird bei Mehrkämpfen wird das aufgegeben kennzeichen anders gesetzt und die Punkteleistungen für den Mehrkampf nicht ausgegeben.

Am Beispiel der Veranstaltung in Weingarten:
https://ladv.de/veranstaltung/detail/21474/Kreis-Mehrkampf-Meisterschaften-U12-und-%C3%A4lter-Weingarten.htm

W14 7-Kampf - aus Ergebnisdaten XML:
![grafik](https://user-images.githubusercontent.com/18612171/136094628-e7026f4a-112c-43ad-b9da-9bc33d46732f.png)

Auszug aus dem XML:
```xml
<round ageclass="W14" compositeevent="NO" event="e9a4f06d3-7596-4e64-9e79-b9c511ea9c81" finalresult="false" id="mh9a4f06d3-7596-4e64-9e79-b9c511ea9c81-W14" indoor="false" roundtype="FINAL" startofeventdate="2021-10-02" startofeventtime="13:00:00.0000000+02:00">
<results>
...
<combinedevent athlete="a7b73dfec-3f07-4533-8242-a761a38a18fb" id="m3c78e0c5-e3e4-4efd-90bc-6032ab9d5901" noncompetitive="false" place="2" result="3329">
<individualreference ref="i9abcb45a-8b2e-4570-8be5-f3a7799e5867"/>
<individualreference ref="i8983e053-79a0-4961-97d3-01891a7e5aed"/>
<individualreference ref="i9fe54897-b2a5-4464-a797-90dedd169917"/>
<individualreference ref="ie693e4a8-a566-472d-ac2d-a81f7175352f"/>
<individualreference ref="i973161e0-53df-4286-82f4-1809c22e5756"/>
<individualreference ref="i48085454-cfcd-487c-8a5f-8356e73891eb"/>
<individualreference ref="ifef41b2e-610d-4a6d-8282-51e225463d29"/>
</combinedevent>
<combinedevent athlete="a1d25629a-73fc-41c3-87aa-36d4f16aaae4" id="mc5d75a68-c467-4c65-ae5d-cb3d3e09972f" noncompetitive="false" place="3" result="a">
<individualreference ref="ic5d7609a-894e-421c-ac43-798ec6848191"/>
<individualreference ref="id48d5195-f9b0-4440-ad34-39a96986111f"/>
<individualreference ref="ife35c7a6-c98f-4ed7-b017-af07d3fdd16a"/>
<individualreference ref="iad8d2ca8-bd60-4249-815c-5da038726ec9"/>
<individualreference ref="ic9dc56c2-4589-45f3-9303-e7dd482e2aa1"/>
<individualreference ref="ia3d8bd6a-8573-4aca-a464-89292892a1a4"/>
<individualreference ref="i5c37e1d5-b942-4375-998a-81809d9178f9"/>
</combinedevent>
<combinedevent athlete="aa30ba0f5-1162-4fe0-82af-1481b9fc5771" id="md8a3e6fa-7723-41ef-8522-bda9e966fe42" noncompetitive="false" place="4" result="a">
<individualreference ref="i30ed8972-00cb-4d70-b7e7-fb90c260c025"/>
<individualreference ref="i0535c3af-a736-4c2e-baa0-b809d6b4fd0a"/>
<individualreference ref="i0c86241d-475f-4b1b-95ba-9b8994919775"/>
<individualreference ref="i79f041c4-e5ce-43a1-b60f-c0d81fc8b019"/>
<individualreference ref="i607e8e27-9f41-401a-b863-cdcd1c241d17"/>
<individualreference ref="i320e794c-0124-41c6-9ba5-b27a25f052a7"/>
<individualreference ref="i24e54ead-8b0b-4d44-bce0-ab606cd210fc"/>
</combinedevent>
```
--> Zwei Athleten (Zimmerling und Schmid) mit "aufg." (aufgegeben).

PDF Ergebnisliste:
![grafik](https://user-images.githubusercontent.com/18612171/136094933-301278e0-2552-4885-9845-ab784ee4e89b.png)

--> Zimmerling und Schmid haben hier Punkte als Mehrkampfleistung und kein aufgegeben.

Erwartung: 
- [ ] die Ausgabe von Punkten oder "aufgegeben" stimmt in PDF und Ergebnisdaten XML überein
- [ ] die feherhaft bereitgestellten Daten werden korrigiert und neu übermittelt

In Vertretung eines Landesstatistikers wird dieser Problembericht erstellt.

**Comment by DocFrag** [comment]
PDF und XML sind bereits seit längerer Zeit synchronisiert

**Comment by mschunk** [comment]
Für die Veranstaltung vom 02./03.10.2021 sind weiterhin keine korrigierten Daten übertragen. Der letzte Stand vom 06.10.2021 02:46:36  enthält immer noch den berichteten Fehler:
![grafik](https://github.com/Deutscher-Leichtathletikverband/Interfaces/assets/18612171/bbc3b708-a104-4d3a-af31-c7d8599f77de)

**Comment by mschunk** [comment]
23K01000000020006 ist eine weitere Betroffene Veranstaltung:
 ![grafik](https://github.com/Deutscher-Leichtathletikverband/Interfaces/assets/18612171/0b5bce25-6d5c-47b5-92d0-8295e5dd5bb8)

Auszug aus dem XML:
```
<round ageclass="W35" compositeevent="NO" event="e35643ad4-5da0-499d-9277-83912ea099b1" finalresult="false" id="mh35643ad4-5da0-499d-9277-83912ea099b1-W35" indoor="false" roundtype="FINAL" startofeventdate="2023-05-13" startofeventtime="13:30:00.0000000+02:00">
<results>
<combinedevent athlete="a5972e958-1905-4789-a16e-5a35a266c232" id="mdfb9f0a6-c995-4466-9ce2-047eae285f0a" noncompetitive="false" place="1" result="a">
<individualreference ref="i885dd22c-5069-42a0-a9ef-59664de067fa"/>
<individualreference ref="i56413f3b-8b88-4f38-a28f-6d0a4ae3aa10"/>
<individualreference ref="i75b64654-883e-4d25-8757-b4474db2a946"/>
<individualreference ref="i591669a0-1ff9-4a77-95f1-4840355649a7"/>
<individualreference ref="ib15f76b0-27a9-496d-8a3a-c1a3ecf7625c"/>
<individualreference ref="i58926a4a-ae50-4a42-86ad-ee9e3957fa86"/>
<individualreference ref="ibe321c03-a14b-4ab4-9fab-6371c1e5657c"/>
</combinedevent>
</results>
</round>
```

Seltec PDF Ergebnisliste:
![grafik](https://github.com/Deutscher-Leichtathletikverband/Interfaces/assets/18612171/812bd2ea-c99a-4d6e-8069-89dc4b8cd8e7)
