### ISSUE TITLE
Public API für DSD, DVD und DED

### ISSUE THREAD

**Issue by malte3d** [Deutscher-Leichtathletikverband/Interfaces#3]
Hallo,

gibt es für die verschiedenen Systeme (DSD, DVD und DED) auch eine Public API und falls ja, wo/wie kann man dafür einen API Key beantragen?

**Comment by UdoLaubDLV** [comment]
Einen API Key können Sie per Mail mit einer kurzen Beschreibung was sie, für welche Zwecke benötigen beantragen.
Mailadressen: udo.laub@leichtathletik.de bzw. alexander.mertens@leichtathletik.de
