### ISSUE TITLE
Unbekannte Veranstaltungskategorie

### ISSUE THREAD

**Issue by santwer** [Deutscher-Leichtathletikverband/Interfaces#6]
Für deutschen Meisterschaften, werden aktuell die EventCategory=220 übertragen. Lt. Schnittstellenbeschreibung 3.03 gibt es diese EventCategory nicht.
Aktuell wäre für uns die Veranstaltung unter EventCategory=35 einzuordnen.

**Comment by mschunk** [comment]
Die Liste der Veranstaltungskategorien ist [hier](https://github.com/Deutscher-Leichtathletikverband/Interfaces#codelisten) zu finden:
Veranstaltungskategorien: [Endpunkt (JSON)](https://dateien.leichtathletik.de/meta/eventcategories) | [Dokumentation](https://dateien.leichtathletik.de/meta/openapidoc#/meta/get_meta_eventcategories)

Für das Update der DLO und der Kategorien siehe [Neue Veranstaltungskategorien](https://github.com/Deutscher-Leichtathletikverband/Veranstaltungen/issues/84)
